headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\bryan\\Documents\\camping-cosmopolite"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/dashboard/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/reserveren"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/dashboard"
to = "/dashboard/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]